use_default_settings:
  engines:
    keep_only:
    - bing
    - duckduckgo
    - brave
    - google
    - yahoo
    - qwant
    - wiby
    - github
    - gitlab
    - hackernews
    - stackoverflow
    - npm
    - pypi
    - sourcehut
    - huggingface
    - wikipedia
    - wikibooks
    - wikiversity
    - wikidata
    - arxiv
    - crossref
    - pubmed
    - semantic scholar
    - openlibrary
    - crowdview
    - lemmy posts
    - lemmy communities
    - docker hub
    - fdroid
    - mwmbl
    - yep
    - searchmysite
    - seznam
    - alpine linux packages
    - anaconda
    - arch linux wiki
    - nixos wiki
    - artic
    - artstation
    - bandcamp
    - baidu
    - bitbucket
    - boardreader
    - bpb
    - openverse
    - media.ccc.de
    - cachy os packages
    - destatis
    - devicons
    - encyclosearch
    - europepmc
    - emojipedia
    - etymonline
    - fireball
    - free software directory
    - fyyd
    - gentoo
    - codeberg
    - gitea.com
    - gmx
    - goodreads
    - google scholar
    - google play apps
    - habrahabr
    - hex
    - crates.io
    - hoogle
    - iconify
    - il post
    - imdb
    - ina
    - jisho
    - lobste.rs
    - lucide
    - mastodon users
    - mdn
    - metacpan
    - microsoft learn
    - mixcloud
    - mankier
    - odysee
    - ollama
    - openairedatasets
    - openairepublications
    - openstreetmap
    - openrepos
    - packagist
    - pdbe
    - photon
    - pub.dev
    - radio browser
    - reuters
    - rottentomatoes
    - sepiasearch
    - sogou
    - soundcloud
    - askubuntu
    - superuser
    - discuss.python
    - caddy.community
    - pi-hole.community
    - privacywall
    - tagesschau
    - tusksearch
    - yandex
    - youtube
    - dailymotion
    - vimeo
    - wikinews
    - wikiquote
    - wikisource
    - wikispecies
    - wiktionary
    - wikivoyage
    - national vulnerability database
    - naver
    - rubygems
    - peertube
    - mediathekviewweb
    - yacy
    - searchch
    - tootfinder
    - voidlinux
    - vuhuv
    - wikimini
    - lib.rs
    - pkg.go.dev
    - minecraft wiki
general:
  instance_name: Searchhh sources
search:
  formats:
  - html
  - json
  safe_search: 0
server:
  bind_address: 0.0.0.0
  port: 8080
  limiter: false
  secret_key: overridden-by-SEARXNG_SECRET
engines:
- name: bing
  disabled: false
- name: duckduckgo
  disabled: false
- name: brave
  disabled: false
- name: google
  disabled: false
- name: yahoo
  disabled: false
- name: qwant
  disabled: false
- name: wiby
  disabled: false
- name: github
  disabled: false
- name: gitlab
  disabled: false
- name: hackernews
  disabled: false
- name: stackoverflow
  disabled: false
- name: npm
  disabled: false
- name: pypi
  disabled: false
- name: sourcehut
  disabled: false
- name: huggingface
  disabled: false
- name: wikipedia
  disabled: false
- name: wikibooks
  disabled: false
- name: wikiversity
  disabled: false
- name: wikidata
  disabled: false
- name: arxiv
  disabled: false
- name: crossref
  disabled: false
- name: pubmed
  disabled: false
- name: semantic scholar
  disabled: false
- name: openlibrary
  disabled: false
- name: crowdview
  disabled: false
- name: lemmy posts
  disabled: false
- name: lemmy communities
  disabled: false
- name: docker hub
  disabled: false
- name: fdroid
  disabled: false
- name: mwmbl
  disabled: false
- name: yep
  disabled: false
- name: searchmysite
  disabled: false
- name: seznam
  disabled: false
- name: alpine linux packages
  disabled: false
- name: anaconda
  disabled: false
- name: arch linux wiki
  disabled: false
- name: nixos wiki
  disabled: false
- name: artic
  disabled: false
- name: artstation
  disabled: false
- name: bandcamp
  disabled: false
- name: baidu
  disabled: false
- name: bitbucket
  disabled: false
- name: boardreader
  disabled: false
- name: bpb
  disabled: false
- name: openverse
  disabled: false
- name: media.ccc.de
  disabled: false
- name: cachy os packages
  disabled: false
- name: destatis
  disabled: false
- name: devicons
  disabled: false
- name: encyclosearch
  disabled: false
- name: europepmc
  disabled: false
- name: emojipedia
  disabled: false
- name: etymonline
  disabled: false
- name: fireball
  disabled: false
- name: free software directory
  disabled: false
- name: fyyd
  disabled: false
- name: gentoo
  disabled: false
- name: codeberg
  disabled: false
- name: gitea.com
  disabled: false
- name: gmx
  disabled: false
- name: goodreads
  disabled: false
- name: google scholar
  disabled: false
- name: google play apps
  disabled: false
- name: habrahabr
  disabled: false
- name: hex
  disabled: false
- name: crates.io
  disabled: false
- name: hoogle
  disabled: false
- name: iconify
  disabled: false
- name: il post
  disabled: false
- name: imdb
  disabled: false
- name: ina
  disabled: false
- name: jisho
  disabled: false
- name: lobste.rs
  disabled: false
- name: lucide
  disabled: false
- name: mastodon users
  disabled: false
- name: mdn
  disabled: false
- name: metacpan
  disabled: false
- name: microsoft learn
  disabled: false
- name: mixcloud
  disabled: false
- name: mankier
  disabled: false
- name: odysee
  disabled: false
- name: ollama
  disabled: false
- name: openairedatasets
  disabled: false
- name: openairepublications
  disabled: false
- name: openstreetmap
  disabled: false
- name: openrepos
  disabled: false
- name: packagist
  disabled: false
- name: pdbe
  disabled: false
- name: photon
  disabled: false
- name: pub.dev
  disabled: false
- name: radio browser
  disabled: false
- name: reuters
  disabled: false
- name: rottentomatoes
  disabled: false
- name: sepiasearch
  disabled: false
- name: sogou
  disabled: false
- name: soundcloud
  disabled: false
- name: askubuntu
  disabled: false
- name: superuser
  disabled: false
- name: discuss.python
  disabled: false
- name: caddy.community
  disabled: false
- name: pi-hole.community
  disabled: false
- name: privacywall
  disabled: false
- name: tagesschau
  disabled: false
- name: tusksearch
  disabled: false
- name: yandex
  disabled: false
- name: youtube
  disabled: false
- name: dailymotion
  disabled: false
- name: vimeo
  disabled: false
- name: wikinews
  disabled: false
- name: wikiquote
  disabled: false
- name: wikisource
  disabled: false
- name: wikispecies
  disabled: false
- name: wiktionary
  disabled: false
- name: wikivoyage
  disabled: false
- name: national vulnerability database
  disabled: false
- name: naver
  disabled: false
- name: rubygems
  disabled: false
- name: peertube
  disabled: false
- name: mediathekviewweb
  disabled: false
- name: yacy
  disabled: false
- name: searchch
  disabled: false
- name: tootfinder
  disabled: false
- name: voidlinux
  disabled: false
- name: vuhuv
  disabled: false
- name: wikimini
  disabled: false
- name: lib.rs
  disabled: false
- name: pkg.go.dev
  disabled: false
- name: minecraft wiki
  disabled: false
